fix Jenkinsfile-build

diff --git a/Jenkinsfile-build b/Jenkinsfile-build
--- a/Jenkinsfile-build
+++ b/Jenkinsfile-build
@@ -11,6 +11,8 @@ pipeline {
         GITHUB_CRED = credentials('github_ssh_key')
         SERVICES = "authservice chatservice messagingservice notificationservice"
         DOCKER_BUILDKIT = '1'
+        DOCKER_CLIENT_TIMEOUT = '600'  // Увеличение клиентского таймаута до 10 минут
+        COMPOSE_HTTP_TIMEOUT = '600'  // Таймаут для Docker Compose
     }
 
     stages {
@@ -62,7 +64,7 @@ pipeline {
 			steps {
 				withCredentials([usernamePassword(credentialsId: 'docker_hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
 					sh '''
-                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
+                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin --timeout=600
                     '''
                 }
             }
@@ -72,62 +74,63 @@ pipeline {
 			steps {
 				sh """
                   docker buildx create --name mybuilder --driver docker-container --use || true
-                  docker buildx inspect mybuilder --bootstrap || exit 1
+                  docker buildx inspect mybuilder --bootstrap --timeout=600 || exit 1
                 """
             }
         }
 
-		stage('Build & Push Docker Images') {
+        stage('Build & Push Docker Images') {
 			steps {
 				script {
 					try {
 						env.SERVICES.split().each { service ->
-							echo "=== Building Docker image for ${service} ==="
-							sh """
-							  docker buildx build \
-								  --platform linux/amd64,linux/arm64 \
-								  --build-arg BUILDKIT_STEP_LOG_MAX_SIZE=104857600 \
-								  -t ${DOCKER_HUB_CREDS_USR}/${service}:${env.BUILD_NUMBER} \
-								  -t ${DOCKER_HUB_CREDS_USR}/${service}:latest \
-								  --push ./services/${service}
-							"""
-						}
-					} catch (Exception e) {
+                            echo "=== Building Docker image for ${service} ==="
+                            sh """
+                              docker buildx build \
+                                  --platform linux/amd64,linux/arm64 \
+                                  --build-arg BUILDKIT_STEP_LOG_MAX_SIZE=104857600 \
+                                  --build-arg BUILDKIT_STEP_LOG_MAX_RETRIES=10 \
+                                  -t ${DOCKER_HUB_CREDS_USR}/${service}:${env.BUILD_NUMBER} \
+                                  -t ${DOCKER_HUB_CREDS_USR}/${service}:latest \
+                                  --push ./services/${service} --timeout=600
+                            """
+                        }
+                    } catch (Exception e) {
 						echo "Error building one of the services: ${e.message}"
-						currentBuild.result = 'FAILURE'
-						error("Build failed for service: ${service}")
-					}
-				}
-			}
-		}
-	}
+                        currentBuild.result = 'FAILURE'
+                        error("Build failed for service: ${service}")
+                    }
+                }
+            }
+        }
+    }
 
-	post {
+    post {
 		success {
 			echo "✅ Build successful!"
-				script {
+            script {
 				writeFile file: 'successful-build-id.txt', text: "${env.BUILD_NUMBER}"
-					archiveArtifacts artifacts: 'successful-build-id.txt', fingerprint: true
-				}
-			}
-		failure {
-		echo "❌ Build failed!"
-			script {
-			archiveArtifacts artifacts: '**/target/*.log', allowEmptyArchive: true
-				sh 'docker logs $(docker ps -lq) || true'
-			}
-		}
-		cleanup {
-		sh """
-			  echo "=== Cleanup ==="
-			  docker logout
-			  if docker buildx ls | grep -q mybuilder; then
-				  echo "Removing Docker Buildx builder 'mybuilder'..."
-				  docker buildx rm mybuilder
-			  else
-				  echo "No builder 'mybuilder' found, skipping removal."
-			  fi
-			"""
-		}
-	}
+                archiveArtifacts artifacts: 'successful-build-id.txt', fingerprint: true
+            }
+        }
+        failure {
+			echo "❌ Build failed!"
+            script {
+				archiveArtifacts artifacts: '**/target/*.log', allowEmptyArchive: true
+                sh 'docker logs $(docker ps -lq) || true'
+            }
+        }
+        cleanup {
+			sh """
+              echo "=== Cleanup ==="
+              docker logout
+              if docker buildx ls | grep -q mybuilder; then
+                  echo "Removing Docker Buildx builder 'mybuilder'..."
+                  docker buildx rm mybuilder
+              else
+                  echo "No builder 'mybuilder' found, skipping removal."
+              fi
+            """
+        }
+    }
 }
